stages:
  - build
  - test
  - package
  - image

variables:
  MAVEN_OPTS: "-Dmaven.repo.local=.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"
  IMAGE_NAME: "$DOCKERHUB_USERNAME/achat-en-ligne-ms"

cache:
  key: "${CI_PROJECT_NAME}"
  paths:
    - .m2/repository

build:
  stage: build
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean compile
  artifacts:
    paths:
      - target/
    expire_in: 1 week

test:
  stage: test
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS test
  artifacts:
    when: always
    reports:
      junit:
        - target/surefire-reports/*.xml
    paths:
      - target/surefire-reports/
    expire_in: 1 week

package:
  stage: package
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS clean package -DskipTests
  artifacts:
    paths:
      - target/*.jar
    expire_in: 1 week

dockerhub-image:
  stage: image
  image: maven:3.9.9-eclipse-temurin-17
  script:
    - mvn $MAVEN_CLI_OPTS compile jib:build -Dimage=$IMAGE_NAME:$CI_COMMIT_SHORT_SHA
    - mvn $MAVEN_CLI_OPTS compile jib:build -Dimage=$IMAGE_NAME:latest
  rules:
    - if: '$CI_COMMIT_BRANCH == "main" || $CI_COMMIT_BRANCH == "master" || $CI_COMMIT_BRANCH == "develop"'